services:
  - type: web
    name: pcm-api
    env: docker
    dockerfilePath: ./Dockerfile
    rootDir: backend
    envVars:
      - key: ASPNETCORE_HTTP_PORTS
        value: 8080
      - key: PORT
        value: 8080
