name: pcm_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.30+30

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  signalr_netcore: ^1.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
